import Head from "next/head";
import React from "react";

const Meta = () => {
    return (
        <Head>
            <title>AzureVDT - Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <meta
                name="keyword"
                content="Thong Dinh, AzureVDT, portfolio, Azuredev"
            />
            <link rel="icon" href="./Favicon.png" />
        </Head>
    );
};

export default Meta;
